import { ClassType, World, Upgrade } from "./types";

export const WORLDS: World[] = [
  {
    id: 0,
    name: "Slime Forest",
    emoji: "🌱",
    minLevel: 1,
    baseExp: 5,
    baseGold: 3,
    monsters: ["Green Slime", "Blue Slime", "King Slime", "Forest Bat"],
  },
  {
    id: 1,
    name: "Goblin Camp",
    emoji: "🔥",
    minLevel: 10,
    baseExp: 25,
    baseGold: 15,
    monsters: ["Goblin Scout", "Goblin Warrior", "Goblin Shaman", "Hobgoblin"],
  },
  {
    id: 2,
    name: "Undead Graveyard",
    emoji: "☠️",
    minLevel: 25,
    baseExp: 100,
    baseGold: 60,
    monsters: ["Skeleton", "Zombie", "Wraith", "Lich Apprentice"],
  },
  {
    id: 3,
    name: "Demon Continent",
    emoji: "😈",
    minLevel: 50,
    baseExp: 500,
    baseGold: 300,
    monsters: ["Imp", "Hellhound", "Succubus", "Demon Commander"],
  },
  {
    id: 4,
    name: "Celestial Realm",
    emoji: "👼",
    minLevel: 100,
    baseExp: 2500,
    baseGold: 1500,
    monsters: ["Lesser Angel", "Cherub", "Seraphim", "Divine Guardian"],
  },
  {
    id: 5,
    name: "Void Dimension",
    emoji: "🌌",
    minLevel: 250,
    baseExp: 15000,
    baseGold: 10000,
    monsters: ["Void Stalker", "Dimension Eater", "Entropy Beast", "Void God"],
  },
];

export const CLASS_EVOLUTIONS: Record<ClassType, ClassType[]> = {
  [ClassType.NOVICE]: [ClassType.SWORDSMAN, ClassType.MAGE, ClassType.ASSASSIN, ClassType.PALADIN, ClassType.NECROMANCER],
  [ClassType.SWORDSMAN]: [ClassType.BLADE_MASTER],
  [ClassType.BLADE_MASTER]: [ClassType.SWORD_GOD],
  [ClassType.SWORD_GOD]: [],
  [ClassType.MAGE]: [ClassType.ARCHMAGE],
  [ClassType.ARCHMAGE]: [ClassType.REALITY_CASTER],
  [ClassType.REALITY_CASTER]: [],
  [ClassType.ASSASSIN]: [ClassType.SHADOW_REAPER],
  [ClassType.SHADOW_REAPER]: [ClassType.DEATH_GOD],
  [ClassType.DEATH_GOD]: [],
  [ClassType.PALADIN]: [ClassType.HOLY_KNIGHT],
  [ClassType.HOLY_KNIGHT]: [ClassType.DIVINE_GUARDIAN],
  [ClassType.DIVINE_GUARDIAN]: [],
  [ClassType.NECROMANCER]: [ClassType.LICH_KING],
  [ClassType.LICH_KING]: [ClassType.GOD_OF_DEATH],
  [ClassType.GOD_OF_DEATH]: [],
};

export const INITIAL_PLAYER = {
  name: "Kean",
  level: 1,
  exp: 0,
  maxExp: 100,
  gold: 0,
  power: 10,
  class: ClassType.NOVICE,
  stats: {
    hp: 100,
    maxHp: 100,
    atk: 10,
    def: 5,
    speed: 5,
    crit: 5,
  },
  rebirths: 0,
  ascensions: 0,
  currentWorld: 0,
  unlockedWorlds: [0],
};
